title: Masatoshi Nishiguchi
tagline: Web Developer
description: Maintainable Web Development using Ruby on Rails and React.
permalink: pretty
url:       "https://mnishiguchi.com"  # Hostname & protocol for your site
baseurl:   ""
repo: https://github.com/mnishiguchi/mnishiguchi.com
author:
  name:              Masatoshi Nishiguchi
  email:             nishiguchi.masa@gmail.com
  url:               https://mnishiguchi.com
  github_url:        https://github.com/mnishiguchi
  linkedin_url:      https://linkedin.com/in/mnishiguchi
  stackoverflow_url: https://stackoverflow.com/users/3837223/mnishiguchi
sass:
  sass_dir: _sass  # Specify the directory that contains sass partials.
  style: :compressed
include:
  - _pages
  - _redirects
exclude:
  - node_modules
  - admin/index.js
plugins:
  - jekyll-gist

# Helpers
navigation_items:
  About: "/"      # /index.html
  Blog:  "/blog/" # /blog/index.html
  Talks: "/talks" # /talks.html
excerpt_separator: <!--more-->
feed: false
empty_array: []
